vgl/about/urls.py
from django.conf.urls import url

from . import views

app_name = 'about'

urlpatterns = [
    url(r'^$', views.about_view, name='about'),
]

vgl/contact/urls.py
from django.conf.urls import url

from . import views

app_name = 'contact'

urlpatterns = [
    url(r'^$', views.contact_view, name='contact'),
]

vgl/home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

vgl/services/urls.py
from django.conf.urls import url

from . import views

app_name = 'services'

urlpatterns = [
    url(r'^$', views.services_view, name='services'),
]

vgl/vgl/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^services/', include('services.urls'), name='services'),
    url(r'^about/', include('about.urls'), name='about'),
    url(r'^contact/', include('contact.urls'), name='contact'),
    url(r'^$', include('home.urls'), name='home'),
]

vgl/about/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

vgl/contact/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

vgl/home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

vgl/services/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

vgl/about/views.py
from django.shortcuts import render


def about_view(request):
    context = {}

    return render(request, 'about/about.html', context)

vgl/contact/views.py
from django.shortcuts import render


def contact_view(request):
    context = {}

    return render(request, 'contact/contact.html', context)

vgl/home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from utils.get_cities import get_cities


def index(request):
    context = {
        'work_radius': get_cities(),
    }

    return render(request, "home/home.html", context)

vgl/services/views.py
from django.shortcuts import render


def services_view(request):
    context = {

    }
    return render(request, 'services/services.html', context)

vgl/templates/about/about.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <title>Valley Green Landscape: About Us</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <!-- Font Awesome  -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Local CSS -->

    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark custom-bg">
      <a class="navbar-brand" href="{% url 'home:index' %}">
        <img src="{% static 'home/img/logo/logo.png' %}" alt="Valley Green Landscape Inc." id="navbar-logo">
        Valley Green Landscape
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto mr-0 text-center">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'services:services' %}">Services <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Testimonials</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'about:about' %}">About Us <span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div>
    </nav>
    <div id="wrapper">
      <div id="header">
        <div class="jumbotron">
          <div class="container text-center">
            <div id="hero-brand">
              <img src="{% static 'home/img/logo/logo.png' %}" alt="Valley Green Landscape Inc." id="hero-logo" class="mb-4">
              <h3 class="text-light">Valley Green Landscape, Inc.</h3>
              <h3><a href="tel:8183621668">(818) 362-1668</a></h3>
            </div>
            <hr class="my-4 hero-hr">
            <h1 id="hero-var-name">About Us</h1>
            <p id="hero-inquiry" class="lead my-0">We are a proud family-owned business with 25+ years of experience.</p>
            <div class="row">
              <div class="col-lg-6 col-md-6 col-sm-8 col-xs-12 mr-auto ml-auto">
                <a class="btn btn-outline-light btn-lg mt-4 btn-block" href="#" role="button">Contact Us</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="content">
        <div class="container">
          <div class="row my-2">
            <div class="col-sm-12">
              <div class="card">
                <img class="card-img-top" src="{% static 'about/img/about-banner.png' %}" alt="Card image cap">
                <div class="card-body">
                  <h2 class="card-title my-4 text-center">Valley Green Landscape, Inc.</h2>
                  <div id="about-paragraph">
                    <p class="card-text">
                      <strong>Cecilio Sandoval</strong> started his journey as a landscape professional in the early 1990s in Los Angeles. He started off as a day laborer, and quickly moved up the ladder to become the supervisor of [insert company name].
                    </p>
                    <p class="card-text">
                       His love for gardening and landscaping made starting his own business an obvious choice. This now thriving business started as a one-man operation called Sandoval Landscaping and his attention to detail quickly won him lifetime clients.
                    </p>
                    <p class="card-text">
                       As business started booming, he expanded his business to include more family members. His sons, <strong>Raymond</strong> and <strong>Kevin Sandoval</strong> grew up watching their father work hard every day and in turn made them also fall in love with the work.
                    </p>
                    <p class="card-text">
                       Wanting to expand the business horizon of the company, <strong>Valley Green Landscape</strong> was born. Valley Green Landscape Incorporated is a family-owned business that is bonded and insured ready to provide both residential and commercial services.
                    </p>
                  </div>
                  <div class="row my-4" id="contact-members">
                    <div class="col-lg-4 text-center">
                      <a href="tel:8185546274" class="btn btn-outline-dark"><strong>Call Cecilio</strong> (818) 554-6274</a>
                    </div>
                    <div class="col-lg-4 text-center">
                      <a href="tel:3239868962" class="btn btn-outline-dark"><strong>Call Raymond</strong> (323) 986-8962</a>
                    </div>
                    <div class="col-lg-4 text-center">
                      <a href="tel:8184478383" class="btn btn-outline-dark"><strong>Call Kevin</strong> (818) 447-8383</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="footer">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 text-center my-3">
              <img src="{% static 'home/img/logo/logo.png' %}" alt="Valley Green Landscape Inc.">
            </div>
          </div>

          <div class="row text-center my-4">
            <div class="col-lg-2">
              <a href="{% url 'home:index' %}">Home</a>
            </div>
            <div class="col-lg-2">
              <a href="{% url 'home:index' %}">Gallery</a>
            </div>
            <div class="col-lg-2">
              <a href="{% url 'services:services' %}">Services</a>
            </div>
            <div class="col-lg-2">
              <a href="{% url 'home:index' %}">Testimonials</a>
            </div>
            <div class="col-lg-2">
              <a href="{% url 'home:index' %}">Contact</a>
            </div>
            <div class="col-lg-2">
              <a href="{% url 'about:about' %}">About Us</a>
            </div>
          </div>

          <div class="row my-4">
            <div class="col-lg-4 text-center">
              <a href="tel:8183621668"><i class="fa fa-phone" aria-hidden="true" style="font-size:20px"></i> (818) 362-1668</a>
            </div>
            <div class="col-lg-4 text-center">
              <a href="mailto:valleygreenlandscapeinc.@gmail.com"><i class="fa fa-envelope" aria-hidden="true" style="font-size:20px"></i> Email Us</a>
            </div>
            <div class="col-lg-4 text-center">
               <a href="https://www.facebook.com/Valley-Green-Landscape-357663454652249/"><i class="fa fa-facebook-official" style="font-size:20px"></i> Valley Green Landscape</a>
            </div>
          </div>

          <div id="copyright" class="row my-3">
            <div class="col-lg-12 text-center">
              Copyright © 2017 Valley Green Lanscape, Inc. All Rights Reserved.
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    <script src="{% static 'home/js/main.js' %}" charset="utf-8"></script>
  </body>
</html>

vgl/templates/contact/contact.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <title>Valley Green Landscape: Contact Us</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <!-- Font Awesome  -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Local CSS -->

    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark custom-bg">
      <a class="navbar-brand" href="{% url 'home:index' %}">
        <img src="{% static 'home/img/logo/logo.png' %}" alt="Valley Green Landscape Inc." id="navbar-logo">
        Valley Green Landscape
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto mr-0 text-center">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'services:services' %}">Services <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Testimonials</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'contact:contact' %}">Contact  <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about:about' %}">About Us</a>
          </li>
        </ul>
      </div>
    </nav>
    <div id="wrapper">
      <div id="header">
        <div class="jumbotron">
          <div class="container text-center">
            <div id="hero-brand">
              <img src="{% static 'home/img/logo/logo.png' %}" alt="Valley Green Landscape Inc." id="hero-logo" class="mb-4">
              <h3 class="text-light">Valley Green Landscape, Inc.</h3>
            </div>
            <hr class="my-4 hero-hr">
            <h1 id="hero-var-name">Contact Us</h1>
            <div class="row">
              <div class="col-lg-12 text-center">
                <h2><i class="fa fa-map-marker"></i> Aztec St. Sylmar, CA 91342</h2>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-12 text-center">
                <h2><i class="fa fa-phone"></i> <a href="tel:8183621668">(818) 362-1668</a></h2>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-12 text-center">
                <h2><a href="mailto:valleygreenlandscapeinc.@gmail.com"><i class="fa fa-envelope"></i> valleygreenlandscapeinc.@gmail.com</a></h2>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="content">
        <div class="container">
          <div class="row my-2">
            <div class="col-sm-12">
              <div class="card">
                <img class="card-img-top" src="{% static 'about/img/about-banner.png' %}" alt="Card image cap">
                <div class="card-body">
                  <h2 class="card-title my-4 text-center">Valley Green Landscape, Inc.</h2>
                  <div id="about-paragraph">
                    <p class="card-text">
                      <strong>Cecilio Sandoval</strong> started his journey as a landscape professional in the early 1990s in Los Angeles. He started off as a day laborer, and quickly moved up the ladder to become the supervisor of [insert company name].
                    </p>
                    <p class="card-text">
                       His love for gardening and landscaping made starting his own business an obvious choice. This now thriving business started as a one-man operation called Sandoval Landscaping and his attention to detail quickly won him lifetime clients.
                    </p>
                    <p class="card-text">
                       As business started booming, he expanded his business to include more family members. His sons, <strong>Raymond</strong> and <strong>Kevin Sandoval</strong> grew up watching their father work hard every day and in turn made them also fall in love with the work.
                    </p>
                    <p class="card-text">
                       Wanting to expand the business horizon of the company, <strong>Valley Green Landscape</strong> was born. Valley Green Landscape Incorporated is a family-owned business that is bonded and insured ready to provide both residential and commercial services.
                    </p>
                  </div>
                  <div class="row my-4" id="contact-members">
                    <div class="col-lg-4 text-center">
                      <a href="tel:8185546274" class="btn btn-outline-dark"><strong>Call Cecilio</strong> (818) 554-6274</a>
                    </div>
                    <div class="col-lg-4 text-center">
                      <a href="tel:3239868962" class="btn btn-outline-dark"><strong>Call Raymond</strong> (323) 986-8962</a>
                    </div>
                    <div class="col-lg-4 text-center">
                      <a href="tel:8184478383" class="btn btn-outline-dark"><strong>Call Kevin</strong> (818) 447-8383</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="footer">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 text-center my-3">
              <img src="{% static 'home/img/logo/logo.png' %}" alt="Valley Green Landscape Inc.">
            </div>
          </div>

          <div class="row text-center my-4">
            <div class="col-lg-2">
              <a href="{% url 'home:index' %}">Home</a>
            </div>
            <div class="col-lg-2">
              <a href="{% url 'home:index' %}">Gallery</a>
            </div>
            <div class="col-lg-2">
              <a href="{% url 'services:services' %}">Services</a>
            </div>
            <div class="col-lg-2">
              <a href="{% url 'home:index' %}">Testimonials</a>
            </div>
            <div class="col-lg-2">
              <a href="{% url 'home:index' %}">Contact</a>
            </div>
            <div class="col-lg-2">
              <a href="{% url 'about:about' %}">About Us</a>
            </div>
          </div>

          <div class="row my-4">
            <div class="col-lg-4 text-center">
              <a href="tel:8183621668"><i class="fa fa-phone" aria-hidden="true" style="font-size:20px"></i> (818) 362-1668</a>
            </div>
            <div class="col-lg-4 text-center">
              <a href="mailto:valleygreenlandscapeinc.@gmail.com"><i class="fa fa-envelope" aria-hidden="true" style="font-size:20px"></i> Email Us</a>
            </div>
            <div class="col-lg-4 text-center">
               <a href="https://www.facebook.com/Valley-Green-Landscape-357663454652249/"><i class="fa fa-facebook-official" style="font-size:20px"></i> Valley Green Landscape</a>
            </div>
          </div>

          <div id="copyright" class="row my-3">
            <div class="col-lg-12 text-center">
              Copyright © 2017 Valley Green Lanscape, Inc. All Rights Reserved.
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    <script src="{% static 'home/js/main.js' %}" charset="utf-8"></script>
  </body>
</html>

vgl/templates/services/services.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <title>Valley Green Landscape: Services</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <!-- Font Awesome  -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!-- Local CSS -->

    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark custom-bg">
      <a class="navbar-brand" href="{% url 'home:index' %}">
        <img src="{% static 'home/img/logo/logo.png' %}" alt="Valley Green Landscape Inc." id="navbar-logo">
        Valley Green Landscape
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto mr-0 text-center">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'services:services' %}">Services <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Testimonials</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about:about' %}">About Us</a>
          </li>
        </ul>
      </div>
    </nav>
    <div id="wrapper">
      <div id="header">
        <div class="jumbotron">
          <div class="container text-center">
            <div id="hero-brand">
              <img src="{% static 'home/img/logo/logo.png' %}" alt="Valley Green Landscape Inc." id="hero-logo" class="mb-4">
              <h3 class="text-light">Valley Green Landscape, Inc.</h3>
              <h3><a href="tel:8183621668">(818) 362-1668</a></h3>
            </div>
            <hr class="my-4 hero-hr">
            <h1 id="hero-var-name">Our Services</h1>
            <p id="hero-inquiry" class="lead my-0">Inquire about residential and commercial projects and get a free estimate.</p>
            <div class="row">
              <div class="col-lg-6 col-md-6 col-sm-8 col-xs-12 mr-auto ml-auto">
                <a class="btn btn-outline-light btn-lg mt-4 btn-block" href="#" role="button">Contact Us</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="content">
        <div class="container">
          <div class="row my-2">
            <div class="col-sm-12">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Gardening Service</h4>
                  <p class="card-text">
                    First impressions matter and one of the best ways to create an inviting home is by taking care of your lawn. This service includes lawn analysis and treatment assessment. We take the pressure off your shoulders by creating a customized plan to improve and maintain the health and look of your grass. This includes: fertilization, insect and weed control, soil aeration and additional services upon request.
                  </p>
                  <div class="service-btns text-right">
                    <a href="#" class="btn btn-outline-success"><i class="fa fa-picture-o" aria-hidden="true"></i> See Photos</a>
                    <a href="#" class="btn btn-outline-primary">Request Service</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row my-2">
            <div class="col-sm-12">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Sodding and Reseeding</h4>
                  <p class="card-text">
                    Got a lackluster lawn and want to do something about it? Start anew by installing new sod or give your current lawn another chance by reseeding it.
                  </p>
                  <div class="service-btns text-right">
                    <a href="#" class="btn btn-outline-success"><i class="fa fa-picture-o" aria-hidden="true"></i> See Photos</a>
                    <a href="#" class="btn btn-outline-primary">Request Service</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="footer">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 text-center my-3">
              <img src="{% static 'home/img/logo/logo.png' %}" alt="Valley Green Landscape Inc.">
            </div>
          </div>

          <div class="row text-center my-4">
            <div class="col-lg-2">
              <a href="{% url 'home:index' %}">Home</a>
            </div>
            <div class="col-lg-2">
              <a href="{% url 'home:index' %}">Gallery</a>
            </div>
            <div class="col-lg-2">
              <a href="{% url 'services:services' %}">Services</a>
            </div>
            <div class="col-lg-2">
              <a href="{% url 'home:index' %}">Testimonials</a>
            </div>
            <div class="col-lg-2">
              <a href="{% url 'home:index' %}">Contact</a>
            </div>
            <div class="col-lg-2">
              <a href="{% url 'about:about' %}">About Us</a>
            </div>
          </div>

          <div class="row my-4">
            <div class="col-lg-4 text-center">
              <a href="tel:8183621668"><i class="fa fa-phone" aria-hidden="true" style="font-size:20px"></i> (818) 362-1668</a>
            </div>
            <div class="col-lg-4 text-center">
              <a href="mailto:valleygreenlandscapeinc.@gmail.com"><i class="fa fa-envelope" aria-hidden="true" style="font-size:20px"></i> Email Us</a>
            </div>
            <div class="col-lg-4 text-center">
               <a href="https://www.facebook.com/Valley-Green-Landscape-357663454652249/"><i class="fa fa-facebook-official" style="font-size:20px"></i> Valley Green Landscape</a>
            </div>
          </div>

          <div id="copyright" class="row my-3">
            <div class="col-lg-12 text-center">
              Copyright © 2017 Valley Green Lanscape, Inc. All Rights Reserved.
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    <script src="{% static 'home/js/main.js' %}" charset="utf-8"></script>
  </body>
</html>